#!/usr/bin/python

if False:
  # see: http://pychecker.sourceforge.net/
  import os
  os.environ['PYCHECKER'] = '--stdlib -100'
  import pychecker.checker


import sys
from optparse import OptionParser
import GG.genteguada

#try:
#  import psyco
#  psyco.full()
#except ImportError:
#  print 'Psyco not installed, the program will just run slower'


# Lectura de parametros de la linea de comandos 
__usage__ = "\n  %s -d directorio destino"%sys.argv[0]
parser = OptionParser( usage = __usage__ )
parser.add_option("-i",dest="ip",help="ip",default=None) 
parser.add_option("-u",dest="user",help="usuario",default="pepe") 
parser.add_option("-p",dest="password",help="clave",default="1234") 
parser.add_option("-f",dest="fullscreen", help="pantalla completa",default=False)
(params, args) = parser.parse_args()

if __name__ == "__main__":
  genteguada = GG.genteguada.GenteGuada()
  genteguada.start(params)
  
