#!/usr/bin/python

if False:
  # see: http://pychecker.sourceforge.net/
  import os
  os.environ['PYCHECKER'] = '--stdlib -100'
  import pychecker.checker


import sys
from optparse import OptionParser
import GG.genteguada
import atexit
import traceback


#try:
#  import psyco
#  psyco.full()
#except ImportError:
#  print 'Psyco not installed, the program will just run slower'


# Lectura de parametros de la linea de comandos 
__usage__ = "\n  %s -d directorio destino"%sys.argv[0]
parser = OptionParser( usage = __usage__ )
parser.add_option("-i",dest="ip",help="ip",default="127.0.0.1") 
parser.add_option("-u",dest="user",help="usuario",default="pepe") 
parser.add_option("-p",dest="password",help="clave",default="1234") 
parser.add_option("-f",dest="fullscreen", help="pantalla completa",default=False)
parser.add_option("-P",dest="port", help="pantalla completa",default=8000, type = int)
(params, args) = parser.parse_args()


import atexit
import traceback


@atexit.register
def goodbye():
  try:
    sys.last_traceback
    f = open("prueba.txt", "w")
    traceback.print_last(limit=None, file=f)
    f.close()
    ggInstance = GG.genteguada.GenteGuada.getInstance()
    ggInstance.finish()
    print "finalizamos la conexion con el server" 
    os.remove("prueba.txt")
  except:
    pass

if __name__ == "__main__":
  genteguada = GG.genteguada.GenteGuada()
  genteguada.start(params)



