#!/usr/bin/python
import dMVC.remoteclient
import pygame
import GG.utils
import GG.model.ggsystem
import time
from pygame.locals import *
import sys
from optparse import OptionParser

class GenteGuada:

  def input(self,events):
    for event in events:
      if event.type == QUIT:
        self.finish()
      if event.type == KEYDOWN:
        if event.key == K_ESCAPE:
          self.finish()
        elif event.key == 13:
          self.isoHud.chatMessageEntered()
        """
        elif event.key == K_q:
          self.sy.insertItemIntoRoom(self.tree, self.player.getRoom(), 0)
        elif event.key == K_a:
          self.sy.removeItem(self.tree, 0)
        elif event.key == K_o:
          self.sy.insertItemIntoRoom(self.girl, self.player.getRoom(), 1)
        elif event.key == K_l:
          self.sy.removeItem(self.girl, 1)
        elif event.key == K_v:
          pass
        """
      if event.type == MOUSEBUTTONDOWN:
        x, y = pygame.mouse.get_pos()
        dest = self.isoHud.getIsoviewRoom().findTile([x,y])
        if dest <> [-1, -1]:
          self.isoHud.getIsoviewRoom().getModel().clickedByPlayer(self.player, [dest[0], 0, dest[1]])
        else:
          self.isoHud.clickedByPlayer(self.player, [x, y])

    self.isoHud.widgetContainer.distribute_events(*events)

  def finish(self):
    print dMVC.utils.statClient.strClient()
    print dMVC.utils.statEventTriggered.strEvent()
    sys.exit(0)

  def start(self,params):
    pygame.init()
    #self.screen = pygame.display.set_mode(GG.utils.SCREEN_SZ,pygame.HWSURFACE|pygame.FULLSCREEN,0)
    self.screen = pygame.display.set_mode(GG.utils.SCREEN_SZ)
    pygame.display.set_caption(GG.utils.VERSION)
    
    if params.execution == "remoto":
      client = dMVC.remoteclient.RClient(params.ip)
      self.sy = client.getRootModel()
    else:
      self.sy = GG.model.ggsystem.GGSystem()

    # Declaraciones solo para pruebas
    #self.tree = GG.model.item.GGItem(GG.utils.OAK_SPRITE, [267, 200], [6, 0, 6], [95, 195])
    #self.girl = GG.model.player.GGPlayer(GG.utils.NINA_SPRITE, GG.utils.NINA_SPRITES, GG.utils.NINO_SZ, [2, 0, 2], [2*GG.utils.CHAR_SZ[0]-75, GG.utils.CHAR_SZ[1]-20], "pepe2", "12345")
                    
    self.session = self.sy.login(params.user, params.password)
    self.player = self.session.getPlayer()
    self.isoHud = self.session.defaultView(self.screen)
    self.isoHud.draw()
    while True:
      time.sleep(GG.utils.ANIM_DELAY)
      self.input(pygame.event.get())
      self.isoHud.updateFrame()
     
# Lectura de parametros de la linea de comandos 
__usage__ = "\n  %s -d directorio destino"%sys.argv[0]
parser = OptionParser( usage = __usage__ )
parser.add_option("-e",dest="execution",help="local/remoto",default="local") 
parser.add_option("-i",dest="ip",help="ip",default="127.0.0.1") 
parser.add_option("-u",dest="user",help="usuario",default="pepe") 
parser.add_option("-p",dest="password",help="clave",default="1234") 
(params, args) = parser.parse_args()

if __name__ == "__main__":
  GenteGuada().start(params)
  
