#!/usr/bin/python

if False:
  # see: http://pychecker.sourceforge.net/
  import os
  os.environ['PYCHECKER'] = '--stdlib -100'
  import pychecker.checker


import GG.model.ggsystem
import dMVC.remoteserver

if __name__ == "__main__":
  def onLogin(rhandler, result, error):
    if result[0]:
      rhandler.ggSession = result[1]
    else:
      rhandler.ggSession = None
  
  def onDisconnection(rhandler):
    if hasattr(rhandler, 'ggSession'):
      if rhandler.ggSession:
        rhandler.ggSession.logout()


  onExecution = [
                  [GG.model.ggsystem.GGSystem, 'login', onLogin]
                ]

  print "Iniciado el servidor del juego Gente Guada"
  dMVC.remoteserver.RServer(GG.model.ggsystem.GGSystem(),
                            onDisconnection = onDisconnection,
                            onExecution = onExecution)
