#!/usr/bin/python

#import sys	
#import models

import GG.model.ggsystem
import dMVC.remoteserver

if __name__ == "__main__":
  rootModel = GG.model.ggsystem.GGSystem()
  dMVC.remoteserver.RServer(rootModel)
