#!/usr/bin/python

#import sys	
#import models


import GG.model.ggsystem
import dMVC.remoteserver

if __name__ == "__main__":
  rootModel = GG.model.ggsystem.GGSystem()
  onExecution = [
                  [GG.model.ggsystem.GGSystem, 'login', rootModel.onLogin]
                ]
  #dMVC.remoteserver.RServer(rootModel,onConnection = rootModel.onConnection, onDisconnection = rootModel.onDisconnection, onExecution = onExecution)
  dMVC.remoteserver.RServer(rootModel, onDisconnection = rootModel.onDisconnection, onExecution = onExecution)
