#!/usr/bin/python

from optparse import OptionParser 
import sys
sys.path.append("../dmvc")
import dMVC.remoteclient

__usage__ = "\n  %s -P puerto"%sys.argv[0]
parser = OptionParser( usage = __usage__ )
parser.add_option("-i",dest="idGift", help="Identificador del regalo")
parser.add_option("-u",dest="username", help="nombre del usuario")
parser.add_option("-p",dest="password", help="clave")
parser.add_option("-U",dest="owner", help="nombre del usuario que tiene el objeto", default=None)
parser.add_option("-I",dest="ip", help="ip del servidor", default="217.12.17.242")
parser.add_option("-P",dest="port", help="puerto del servidor", default=770, type=int)
(params, args) = parser.parse_args()

try:
  client = dMVC.remoteclient.RClient(params.ip, port = params.port)
except Exception, excep:
  print "No se pudo conectar con el servidor"
  sys.exit()

system = client.getRootModel()

if system.loginGuadalinex(params.username, params.password) == "A":
  if system.deleteGift(params.idGift, params.owner):
    print "Objeto eliminado con exito"
  else:
    print "Objeto no encontrado"
else:
  print "Usuario no existente o sin permisos"    