#!/usr/bin/python

import dMVC.remoteclient

if __name__ == "__main__":
  client = dMVC.remoteclient.RClient("127.0.0.1")
  model = client.getRootModel()
  print model
  """
  gg = ggclient.gg.GG()
  gg.start()  
  """
  
