#!/usr/bin/python

import sys	

sys.path.append("/usr/share/genteguada-client")
sys.path.append("../common")

#from ggclient.gg import *
import ggclient.gg

if __name__ == "__main__":
  gg = ggclient.gg.GG()
  gg.start()  
    
  
