#!/usr/bin/python

import sys
sys.path.append("../../dmvc")

import models
import dMVC.remoteserver

if __name__ == "__main__":
  rootModel = models.TestModel()
  dMVC.remoteserver.RServer(rootModel)
