#!/usr/bin/python

import sys	

sys.path.append("/usr/share/genteguada-server")
sys.path.append("../common")
sys.path.append("../test")

import ggserver.remoteserver
import models


if __name__ == "__main__":
  rootModel = models.TestModel()
  ggserver.remoteserver.RServer(rootModel)
