#!/usr/bin/python

import sys	

sys.path.append("/usr/share/genteguada-server")
sys.path.append("../common")

import ggserver.testmodel
import ggserver.remoteserver

if __name__ == "__main__":
  rootModel = ggserver.testmodel.TestModel()
  server = ggserver.remoteserver.RServer(rootModel)
  #ggServer = ggserver.server.Server()
  #ggServer.start()  

