#!/usr/bin/python

import sys	

sys.path.append("/usr/share/genteguada-server")
sys.path.append("../common")

import ggserver.server

if __name__ == "__main__":
  ggServer = ggserver.server.Server()
  ggServer.start()  

