#!/usr/bin/python

import sys
import time
import pygame
import utils
from pygame.locals import *

import ggsystem

def input(events):
  for event in events:
    if event.type == QUIT: 
      sys.exit(0)
    if event.type == KEYDOWN and event.key == K_ESCAPE:
      sys.exit(0)
      
def input(events, room, player, isoviewroom):
  for event in events:
    if event.type == QUIT: 
      sys.exit(0)
    if event.type == KEYDOWN and event.key == K_ESCAPE:
      sys.exit(0)
    if event.type == MOUSEBUTTONDOWN:
      x, y = pygame.mouse.get_pos()
      dest = isoviewroom.findTile([x,y])
      if dest <> [-1, -1]:
        room.clickedByPlayer(player, [dest[0], 0, dest[1]])
        #self.room.clickedByPlayer(self.activePlayer, [dest[0], 0, dest[1]])
      

if __name__ == "__main__":
  
  pygame.init()
  screen = pygame.display.set_mode(utils.SCREEN_SZ)
  pygame.display.set_caption(utils.VERSION)
  
  sy = ggsystem.GGSystem()
  session = sy.login("pepe", "1234")
  player = session.getPlayer()
  room = player.getCurrentRoom()
  isoviewroom = room.defaultView(screen)
  
  isoviewroom.drawFirst()
  pygame.display.update()
  
  while True:
    time.sleep(utils.TICK_DELAY)
    input(pygame.event.get(), room, player, isoviewroom)
    sy.tick()
    